### ISSUE TITLE
CORS works on Chrome but not Safari

### ISSUE THREAD

**Issue by dagatsoin** [xcv58/meteor-collectionapi#10]
Hi,

I have issue with CORS. If you try access this url http://tourisme-ploermel.com/?debug=true in chrome then in Safari. It works with Chrome but not in Safari. Neither on iOS. Did not try on Android.

Here is a log of my server
```
Error: Can't set headers after they are sent.
2015-07-21T19:49:45.688+02:00at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
2015-07-21T19:49:45.717+02:00at ServerResponse.res.setHeader (/home/bas/app_a5ad6cc6-7305-4134-a6d7-da32daf6a1e6/my_app/node_modules/connect/lib/patch.js:59:22)
2015-07-21T19:49:45.731+02:00at packages/xcv58:collection-api/xcv58:collection-api.js:76:1
```

Any idea ?

**Comment by dagatsoin** [comment]
This [SO ansxer](http://stackoverflow.com/a/22924272/3656447) suggest to add  `Allowed-Header : origin`

**Comment by xcv58** [comment]
I'm not sure what causes your issue.

But I double check on Chrome, Safari, Safari of iOS. They all work.

Could you share your repo link for site: http://tourisme-ploermel.com/?debug=true
So I can double check your setup.

You must manually set ```allowCORS``` to ```true``` when ```new CollectionAPI```

**Comment by dagatsoin** [comment]
Did you check from my link?

My repo is not on tourisme-ploermel. It is hosted on clever-cloud.com.

I have multiple sites: tourisme-ploermel.com/?debug=true, mairie-elven.fr/?debug=true using this script: ranger-analytics.com/js/ranger.js

This file calls the api on ranger-analytics.com

With Chrome at this url: `http://www.mairie-elven.fr/?debug=true`
```
www.ranger-analytics.com/js/ranger.js:79 1 - 0
www.ranger-analytics.com/js/ranger.js:79 2 - 201
www.ranger-analytics.com/js/ranger.js:79 3 - 201
www.ranger-analytics.com/js/ranger.js:79 4 - 201
www.ranger-analytics.com/js/ranger.js:81 [{"_id":"8CAPxrmRby6MEfJCK","loc":{"type":"Point","coordinates":[2.35,48.86]},"geoip":true,"offline":false,"date":"2015-07-21T20:12:28.372Z","organizationId":"000000003","trackerId":"RG-000000003-1","visitor":{"returning":true,"uuid":"93f22f57-3853-4743-8541-f92c49c2aa38","navigator":{"appCodeName":"Mozilla","appName":"Netscape","appVersion":"5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36","language":"fr","platform":"MacIntel","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36"}}}]
```
With Safari at this url: `http://www.mairie-elven.fr/?debug=true`
```
[Log] 1 - 0 (ranger.js, line 79)
[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (traces, line 0)
[Error] Failed to load resource: Origin http://tourisme-ploermel.com is not allowed by Access-Control-Allow-Origin. (traces, line 0)
[Error] XMLHttpRequest cannot load http://ranger-analytics.com/collectionapi/traces. Origin http://tourisme-ploermel.com is not allowed by Access-Control-Allow-Origin. (tourisme-ploermel.com, line 0)
[Log] 4 - 0 (ranger.js, line 79)
```
Tried from two different Mac.

**Comment by xcv58** [comment]
I do test your links.

It doen't work in all browsers. I think it's the same issue #6 
The clever-cloud.com, like herokuapp.com, may rewrite http request header for security reason.

Could you deploy your website in 

1. local, or
2. your server, or
3. meteor official server

and have a try?

**Comment by dagatsoin** [comment]
Well, I duplicated my app to ranger.meteor.com

I tried from this URL http://domino-studios.com/testranger.html?debug=false

Both on Chrome and Safari and I have got the same result:

Chrome:
```
1 - 0
ranger.js:79 2 - 201
ranger.js:79 3 - 201
ranger.js:79 4 - 201
ranger.js:81 [{"_id":"PCL6rqW5Mavp4xty3","loc":{"type":"Point","coordinates":[2.35,48.86]},"geoip":true,"offline":false,"date":"2015-07-21T21:24:29.316Z","organizationId":"DEMO","trackerId":"RG-DEMO-1","visitor":{"returning":true,"uuid":"5585ddd2-e654-4864-b1ef-5f90c0ff4a38","navigator":{"appCodeName":"Mozilla","appName":"Netscape","appVersion":"5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36","language":"fr","platform":"MacIntel","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36"}}}]
```
Safari
```
1 - 0
http://ranger-analytics.com/collectionapi/tracesFailed to load resource: the server responded with a status of 502 (Bad Gateway)
http://ranger-analytics.com/collectionapi/tracesFailed to load resource: Origin http://domino-studios.com is not allowed by Access-Control-Allow-Origin.
testranger.html:1XMLHttpRequest cannot load http://ranger-analytics.com/collectionapi/traces. Origin http://domino-studios.com is not allowed by Access-Control-Allow-Origin.
ranger.js:794 - 0
```

**Comment by xcv58** [comment]
Probably you misunderstand how CORS works.

For example, there're two websites: A and B. You own B and somebody else own A.

You can't access A from B if A doesn't support CORS from B. Whatever you config B doesn't affect A's response.

One possible way is issue HTTP request from B's (yours) server.

**Comment by dagatsoin** [comment]
But in this case, why there is a different behavior between using Safari and Chrome ? If A doesn't support CORS from B, whatever the browser I use I should get the same error. But it is not the case. It works with Chrome but not with Safari.

I redeployed my app to Meteor. I will be my dev environment while Clevercloud is still my prod environment.

I get the same behavior in the two configurations visiting this url `http://mairie-elven.fr/?debug=true` (succes with Chrome, error 502 with Safari)

**Comment by xcv58** [comment]
I tried your link: http://mairie-elven.fr/?debug=true
It doesn't work for both Chrome and Safari.
It says:

```
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Could you tell me the detail you access the link: http://mairie-elven.fr/?debug=true
like: from which url, how to issue http request?

**Comment by dagatsoin** [comment]
I directly paste http://mairie-elven.fr/?debug=true in the browser from my desktop.

**Comment by xcv58** [comment]
In my computer: it works on both Chrome and Safari:
![screenshot 2015-07-22 13 45 37](https://cloud.githubusercontent.com/assets/503123/8832637/2e88e600-3078-11e5-9138-c4ba4f16d36d.png)
![screenshot 2015-07-22 13 45 19](https://cloud.githubusercontent.com/assets/503123/8832638/2ea292bc-3078-11e5-9419-ca53afa5d9f9.png)

**Comment by dagatsoin** [comment]
0_0 don't understand anything.
It seems to be a random behavior.
Look, I will contact the support of Clever Cloud to get an answer of the log error first. I will give them this issue URL.

**Comment by xcv58** [comment]
Sorry for misunderstanding, I thought you wanna access http://mairie-elven.fr/?debug=true from another site. 

It seems you wanna access
```
  url = "http://ranger-analytics.com/";
```
and
```
  url = "http://ranger.meteor.com/";
```
from http://mairie-elven.fr/?debug=true

But you might wanna try my meteor site:
http://xcv58.meteor.com
If you set:
```
  url = "http://xcv58.meteor.com/collectionapi/players";
```
you can always get response.

But if you set
```
  url = "http://xcv58.meteor.com/";
```
you can NOT get response.

Because the collection-api will only rewrite http header for url with its specific path.

**Comment by dagatsoin** [comment]
The URL you have past is just to switch between dev/prod/local environment via a GET variables.

Then it will form a complete URL when sending the request `xhr.open(method, url+"collectionapi/traces", true);`

**Comment by xcv58** [comment]
I try http://ranger-analytics.com/collectionapi/traces 
It said:

Please wait

This application is starting, you will be redirected once it is ready.

If your are the application owner, check your logs for details.

**Comment by dagatsoin** [comment]
Yep, the database got too big. Each direct access make the app craches :/ (don't be evil :)

**Comment by xcv58** [comment]
Yes, I understand this. When I deploy my first meteor project. It'll crash after few requests just because the server didn't have enough memory.

**Comment by dagatsoin** [comment]
Here is a response from the support. I will try to translate it correctly.

"This is a Node error when trying to add headers instruction after the response has began to be sent. It could be random because of the asynchronous waterfall. It could be a coding problem. The use of libs like Bluebird or Promise could resolve this."

Your opinons ? (FYI he did not see your code)

**Comment by xcv58** [comment]
It sounds reasonable. Because I occasionally see error like set header after it send.

I'll try recreate it and try to fix it.

**Comment by dagatsoin** [comment]
Cool. If you need help I am your man. I will be full focus on my project for the weeks to come. So just tell me what to do.

Envoyé de mon iPhone

**Comment by xcv58** [comment]
I publish v0.2.4
It should fix your issue, if it caused by add headers instruction after response send.

**Comment by dagatsoin** [comment]
Great news. When will I be able to update it? For now meteor still download 0.2.3
`Collection API v0.2.3 running at /collectionapi`

**Comment by xcv58** [comment]
Did you try
meteor update

**Comment by dagatsoin** [comment]
yep

**Comment by xcv58** [comment]
It's already there:
https://atmospherejs.com/xcv58/collection-api

**Comment by dagatsoin** [comment]
Yep and when I have done meteor update it wrote `xcv58:collection-api  added, version 0.2.4    
` but when I launch it it is still `Collection API v0.2.3 running at /collectionapi`. Also I have still headers erros once deployed online.

**Comment by xcv58** [comment]
I forget change the string.

So it's the same situation, works on Chrome but not on Safari?

**Comment by dagatsoin** [comment]
Yes. But Safari receives another error now: `[Error] Failed to load resource: the server responded with a status of 501 (Not Implemented) (traces, line 0)`

**Comment by xcv58** [comment]
Could you tell me the version of Mac OS and Safari?
I'll try to recreate error in virtual machine.

**Comment by dagatsoin** [comment]
I use Chrome 43.0.2357.134 and Safari 8.0.7 on a MacBook Pro mid 2010 with OSX 10.10.4 (14E46)

I also tried on a iMac and a Windows PC but I have note the version right now.

Interesting fact: I have not any header errors in my server logs. So don't care about my first feedback! Things are on the right way!

**Comment by xcv58** [comment]
Could you tell me which url you reuqest?
Is it http://ranger-analytics.com/collectionapi/traces ?

**Comment by dagatsoin** [comment]
yep

**Comment by xcv58** [comment]
I can't get response even use ```curl``` from this url.

**Comment by xcv58** [comment]
Could you give me an id, so that I can get only one document.

**Comment by dagatsoin** [comment]
And I have not any success with Chrome anymore...

Wait I will only allow POST access. In case of blocked app.

**Comment by xcv58** [comment]
OK.
Like this:
```
curl http://xcv58.meteor.com/collectionapi/players/aescW3iB9W4k2rusR
```

Actually, you can use ```before``` function for ```GET``` to ban all requests without a ```collectionId``` in ```requestMetadata```

**Comment by dagatsoin** [comment]
I reopened the GET access, here is an id GCE5hWXdBxjFJQnXy

**Comment by xcv58** [comment]
It's ```501``` again.
Could you double check:
```
      methods: ['POST','GET','PUT','DELETE'],  // Allow creating, reading, updating, and deleting
```
Whether have ```'GET'``` in your code?

**Comment by xcv58** [comment]
BTW: 
My OS: OS X EI Capitan 10.11 Beta (15A226f)
Safari: Version 9.0 (11601.1.39.0.2)
Chrome: 45.0.2454.12 (Official Build) dev (64-bit)

**Comment by dagatsoin** [comment]
Ok I have something:

Here is a simpler test case based of a script of your (I simply add the `JSON.stringify()` ):
```
<!DOCTYPE html>
<html>
<head>
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script>
    function test() {
        $.ajax({
            type:'POST',
            url: "http://ranger-analytics.com/collectionapi/traces",
            data: JSON.stringify({
                "todelete":true,
                "long":-2.275,
                "lat":48.08560
            }),
            contentType:'text/plain',
            xhrFields:{
                withCredentials:false
            },
            success: function(res, status, xhr){console.log( 'Successful cross-domain AJAX request.' );
                console.log(xhr);
                console.log(JSON.stringify(res));
                console.log(status);
            },
            error: function(e){console.log( e );},
        });
    }
  </script>
</head>

<body>
  <button type="button" onclick="test()">Button</button>
</body>
</html>
```
You can test it here http://domino-studios.com/testrest.html It works on Chrome and Safari.

I will investigate the difference between this jQuery code and my vanilla JS code. Maybe the encoding part ?

**Comment by xcv58** [comment]
Your site is down again...

**Comment by dagatsoin** [comment]
I think the database is too big. I am done for tonight. I will flush the database tomorrow and continue to compare the code. I think we can close the ticket now since server headers errors are gone. Thx so much for your time!

**Comment by xcv58** [comment]
Cool, thank you for catch the bug.

Below is my advise to handle big database:
1. use before function to block ```GET``` request with all documents
or
2. manually handle ```GET``` by using ```returnObject``` in before function, so that you can return a fixed size of documents

**Comment by dagatsoin** [comment]
Yep I put this on my todo for tomorrow!
