### ISSUE TITLE
Comparison with nimble:restivus

### ISSUE THREAD

**Issue by dandv** [xcv58/meteor-collectionapi#12]
Now that [nimble:restivus](https://github.com/kahmali/meteor-restivus) has released a version without iron:router, and has received contributions from MDG core dev @stubailo, should this package be deprecated?

**Comment by xcv58** [comment]
I haven't really use the [nimble:restivus](https://github.com/kahmali/meteor-restivus).

I use this package in my own project to achieve some custom logic. I'm not sure I can move my codes qucikly.

**Comment by xcv58** [comment]
I can add deprecated declaration in README.md if you really want.

**Comment by stubailo** [comment]
@dandv I don't know that my having contributed to a package means that everyone else should pack up and leave.

But it could be good to do a comparison between this package and Restivus, and see what the differences are.
