### ISSUE TITLE
how to use versions

### ISSUE THREAD

**Issue by dtruel** [xcv58/meteor-collectionapi#18]
hello,

for apiPath, I wrote `api/v1`, and I get a 404.  Is there any way you can set it so that I can add a slash in there to specify versions?

**Comment by xcv58** [comment]
I use `/api-v1`, `/api-v2` to indicate different versions.

**Comment by xcv58** [comment]
Sorry for the inconvenience, the routing logic is hard coded in current implementation. It wouldn't change before Meteor 1.3 is released.

**Comment by dtruel** [comment]
ok, thanks!
