### ISSUE TITLE
How to create Meteor RESTful Authentication ?

### ISSUE THREAD

**Issue by Jayuda** [xcv58/meteor-collectionapi#21]
Hello i want implement REST with username & password for user authentication.
I Have read this source [https://github.com/534N/apitest](https://github.com/534N/apitest). But i dont sucess with that.
Please help. Thanks

**Comment by xcv58** [comment]
I suggest that always use token based authentication.

You need to provide an authenicate function: https://github.com/xcv58/meteor-collectionapi#custom-authenticate-function  this will send the token to you.

About how to get the token: you can provide web UI for this. Or you can implement a RESTful endpoint for this. The `before` function can help you to check whether it's correct user.

**Comment by Jayuda** [comment]
Thanks for your informations
