### ISSUE TITLE
How to implement after POST

### ISSUE THREAD

**Issue by Jayuda** [xcv58/meteor-collectionapi#23]
Hello @xcv58 ,
i am confused on implement AFTER POST. Can i get data content POST on function after ?
please give me example to use it.
thanks a lot

**Comment by xcv58** [comment]
@Jayuda Current implementation doesn't pass any data to the `after` functions. But I'm working on a ES6 style version which only support Meteor 1.3 and later.

Could you tell me what you need?

If you want to manipulate your data for `POST`, I suggest that you use the `before` function. It'll provide better performance.

Thanks!

**Comment by Jayuda** [comment]
Ok, thanks @xcv58, 
I am implement on `before` and its work well
thanks a lot
