### ISSUE TITLE
CollectionAPI is not defined

### ISSUE THREAD

**Issue by Jaetoh** [xcv58/meteor-collectionapi#27]
Hi ! 

I just add the packages to my meteor project and ran this simple code : 
```

Meteor.startup( function() {

    collectionApi = new CollectionAPI({ authToken: '97f0ad9e24ca5e0408a269748d7fe0a0' });
    collectionApi.addCollection(json, 'json_collection');
    collectionApi.start();

 });
```

But i have the error "CollectionAPI is not defined". I really don't know how to solve this problem, i'm still wondering what's wrong since 2 hours.

**Comment by xcv58** [comment]
What's your Meteor version?

If it's greater than 1.3, you may need this line:
```js
import { CollectionAPI } from 'meteor/xcv58:collection-api';
```
Please refer: https://github.com/xcv58/meteor-collectionapi/blob/master/examples/test-app/server/main.js#L2

**Comment by Jaetoh** [comment]
I run 1.3.2 ! Thanks, it works !

**Comment by xcv58** [comment]
Great!
