### ISSUE TITLE
Current version does not support Meteor1.3 Version?

### ISSUE THREAD

**Issue by willygwu** [xcv58/meteor-collectionapi#28]
I got the following erro message.

While checking for xcv58:collection-api@0.3.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

**Comment by xcv58** [comment]
What's your OS version?

**Comment by willygwu** [comment]
Windows 10

**Comment by xcv58** [comment]
Could you try again?

I tried to publish this package for Windows. But I'm not sure whether it works because I don't have a Windows machine/VM.

Otherwise, you can try to use `v0.2.6`. It's the same as `v0.3.0`. The only difference is that `v0.3.0` is written in ES6 style.

**Comment by willygwu** [comment]
0.2.6 version works!!, but 3.0 still dose not work.
Thanks ^^

**Comment by xcv58** [comment]
Great. I need a Windows VM to debug the 0.3.0 version.

**Comment by genyx** [comment]
Same here on Win10.
Using
`meteor add xcv58:collection-api@=0.2.6`
works.
