### ISSUE TITLE
How to deal with Accounts?

### ISSUE THREAD

**Issue by willygwu** [xcv58/meteor-collectionapi#29]
I did like this

collectionApi.addCollection(Accounts, 'accounts', {
     .....
});

and then 

$ curl -H 'X-Auth-Token: 97f0ad9e24ca5e0408a269748d7fe0a0' -d "{ new user info goes here}" http://127.0.0.1:3000/collectionapi/accounts

then I got this message

{"error":"TypeError: Object [object Object] has no method 'insert'"}

**Comment by xcv58** [comment]
You cannot use Accounts directly. Because it's not an ordinary Collection. You'd better use the before hook to handle request by yourself. Otherwise you can use a custom Collection for your account.
