### ISSUE TITLE
fields and query not working ?

### ISSUE THREAD

**Issue by AbdelMounhim** [xcv58/meteor-collectionapi#32]
Hi,
i just installed your module and it's working great with MeteorJS 1.4.2 except for filtering object queries.

i have a mongodb collection  named "commands" 
i would like to be able to query the api with 2 fields (here pole and dateParution).

sample of query : 
db.commands.find({"pole":"INTERNATIONAL", "dateParution" : "20170109" }, {"title" : 1 , "dateParution" : 1})

GET http://localhost:3001/api/commands  : OK (returns all the objects in database)

requestMetadata OK (no collectionId here) : 
 {"collectionPath":"commands",
    "fields":[],
    "query":{}
}

GET http://localhost:3001/api/commands/HXqzEiQFtqSMizMLG  : OK  (returns the content of the object which _id = HXqzEiQFtqSMizMLG )

requestMetadata : 
 {"collectionPath":"commands",
   "collectionId":"HXqzEiQFtqSMizMLG",
    "fields":[],"query":{}
}

But if a try to query only some objects, following the documentation 

http://localhost:3000/collectionapi/players/id/a/b/c\?x\=1\&y\=2\&c\=3

it's not working : 

GET http://localhost:3001/api/commands/title/dateParution\?pole\=INTERNATIONAL

in the requestMetadata obtained, collectionId and fields are wrong  
{       
            "collectionPath":"commands", 
            "collectionId":"title",
            "fields":["dateParution"],
            "query":{"pole":"INTERNATIONAL"}
}

the correct values should be : 
{       
            "collectionPath":"commands", 
            "collectionId": undefined,
            "fields":["title", "dateParution"],
            "query":{"pole":"INTERNATIONAL"}
}

how can i specify that collectionId is empty (or undefined)  ? 

if i try to get all command with pole = INTERNATIONAL : 
http://localhost:3001/api/commands/\?pole\=INTERNATIONAL

requestMetadata is correct : 
{"collectionPath":"commands",
  "fields":[],
   "query":{"pole":"INTERNATIONAL"}
}
but the result of the query is all the objects in database (the query params are ignored in fact).

Thanks

**Comment by xcv58** [comment]
Hi @AbdelMounhim,

According to your question for URL id mapping.

it's not working :

GET http://localhost:3001/api/commands/title/dateParution\?pole\=INTERNATIONAL

in the requestMetadata obtained, collectionId and fields are wrong
```json
{
"collectionPath":"commands",
"collectionId":"title",
"fields":["dateParution"],
"query":{"pole":"INTERNATIONAL"}
}
```

the correct values should be :
```json
{
"collectionPath":"commands",
"collectionId": undefined,
"fields":["title", "dateParution"],
"query":{"pole":"INTERNATIONAL"}
}
```

I'm afraid I can't help you too much. Because the RESTful API should specific id after resources. The assumption is that if your URL path looks like this `/api/:resources/:rest`, the `:rest` is the id of the resources.

Could you try put the `title/dateParution` as query parameters instead of part of URL path?

**Comment by AbdelMounhim** [comment]
Thanks @xcv58 for your answer.

i still don't really understand what is the collectionId in my case. 
i succeed with your api to list all objects but not only objects filtered with a query.
and i don't know what is the collectionId for me in this case ?

as explained, even if i don't specify fields,  but just query params  like this :  http://localhost:3001/api/commands/\?pole\=INTERNATIONAL
(all commands that have the field POLE equals to "INTERNATIONAL") the API returns me all objects in the mongoDB  and not just the commands with POLE = INTERNATIONAL.

**Comment by xcv58** [comment]
I got your idea.

Because the package doesn't automatically support field query.
You have to use the [Handle all requests by yourself](https://github.com/xcv58/meteor-collectionapi#handle-all-requests-by-yourself) feature to build your own query.

**Comment by AbdelMounhim** [comment]
ok. Thanks you very much for your help

**Comment by surfer77** [comment]
hi @AbdelMounhim did you find the answer to your problem? I am having the same exact problem,  I can't query a single item.
thanks

**Comment by AbdelMounhim** [comment]
hi @surfer77 
i didn't succeed to query one item. 
I switch to another api ( simple:rest ) which is working out of the box.
