### ISSUE TITLE
No compatible binary for 1.4.2.3

### ISSUE THREAD

**Issue by morphogencc** [xcv58/meteor-collectionapi#33]
Hello!  I found your package from the [Meteorpedia REST page](http://www.meteorpedia.com/read/REST_API), and tried to install it for use on my app.

Unfortunately, when I tried to install it on my app, it failed and said there was no compatible binary:

```
C:\meteor\simple-app>meteor add xcv58:collection-api
 => Errors while adding packages:

While checking for xcv58:collection-api@0.3.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

I'm brand-new to Meteor, so unfortunately I'm not able to be more helpful than this -- when will a binary come out for the newest version?

**Comment by xcv58** [comment]
Hi @morphogencc, I think the #28 will answer your question in details. The short answer is that there is **no difference** between 0.2.6 and 0.3.0

Sorry for the inconvenience. I'm really want to setup a Windows environment if I have time.

**Comment by morphogencc** [comment]
Great!  I just tried it and it installs perfectly.  thanks!

**Comment by xcv58** [comment]
Cool, have fun!
