### ISSUE TITLE
Comparison with restivus

### ISSUE THREAD

**Issue by dandv** [xcv58/meteor-collectionapi#8]
How does this package compare with @kahmali's [nimble:restivus](https://github.com/kahmali/meteor-restivus) ?

**Comment by xcv58** [comment]
I have tried [nimble:restivus](https://github.com/kahmali/meteor-restivus).

It seems restivus have more features than meteor-collectionapi, like Route support.

But meteor-collectionapi is relatively simple, at least for me. Later on I add some useful features like [Custom Authenticate Function](https://github.com/xcv58/meteor-collectionapi#custom-authenticate-function), [Handle all requests by yourself](https://github.com/xcv58/meteor-collectionapi#handle-all-requests-by-yourself).

I use those features in my project and will keep develop this project.

But I don't know which one is match your goal. If you just need provide simple RESTful APIs, probably this one is better. If you need some advanced features like [Endpoint](https://github.com/kahmali/meteor-restivus#endpoint-configuration), [nimble:restivus](https://github.com/kahmali/meteor-restivus) is better.

**Comment by dandv** [comment]
Thanks @xcv58. I want to be able to return a transformed version of a document with getAll and get requests. For example, change the value of a field in a document.

**Comment by xcv58** [comment]
If you use meteor-collectionapi, to achieve is easy.
You just need custom the ```GET``` function in ```before``` [quick setup](https://github.com/xcv58/meteor-collectionapi/blob/master/README.md#quick-setup)

```javascript
  GET: function(objs, requestMetadata, returnObject) {
    // change objs (it's an array), and it will return changed version of objs
    // getAll and get is the same thing here:
    // getAll will pass objs with all objects, get will pass objs with one object
    return true;
  },
```
