### ISSUE TITLE
how to print output with pretty json

### ISSUE THREAD

**Issue by sintret** [xcv58/meteor-collectionapi#9]
i like this extensions but could you add --prettyjson ?

thanks

**Comment by xcv58** [comment]
I don't think the json format feature should be included in this package.

The users can use different tech to format the json string.
For me, I use Emacs package: [gongo/json-reformat](https://github.com/gongo/json-reformat) to reformat result.

There're many methods to reformat the json string, but it depends which tool the developer used.

**Comment by sintret** [comment]
I see good idea for custom json output, thanks for quick response...

**Comment by xcv58** [comment]
You're very welcome.
